apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pmcy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-pmcy
    app.kubernetes.io/part-of: test-rhtap-30-app
  name: devfile-sample-code-with-quarkus-pmcy
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-pmcy
status:
  loadBalancer: {}
